version: '3'

services:
  # Database
  db:
    image: 'mysql:${MYSQL_VERSION}'
    volumes:
      - db_data:/var/lib/mariadb
      - ./tema_apolo.sql:/docker-entrypoint-initdb.d/tema_apolo.sql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    networks:
      - wpsite
  # phpmyadmin
  mariadb:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - '${DB_PORT}:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${SERVER_PORT}:80"
    restart: "no"
    volumes:
      - ./public:/var/www/html/public
    environment:
      WORDPRESS_DB_HOST: ${PROJECT_NAME}_wordpress
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_DATABASE}'
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
