version: '3'

services:
  # Database
  db:
    image: 'mysql:${MYSQL_VERSION}'
    volumes:
      - db_data:/var/lib/mariadb
      - ./tema_apolo.sql:/docker-entrypoint-initdb.d/tema_apolo.sql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      MYSQL_DATABASE: '${WORDPRESS_DB_NAME}'
      MYSQL_USER: '${WORDPRESS_DB_USER}'
      MYSQL_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
    networks:
      - wpsite
  # phpmyadmin
  mariadb:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - '${WORDPRESS_DB_PORT}:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${SERVER_PORT}:80"
    restart: "no"
    volumes: [ './public:/var/www/html' ]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
